### ISSUE TITLE
Paper Wallet Sweep on Bitcoin Testnet not completing

### ISSUE THREAD

**Issue by HashEngineering** [coreyphillips/moonshine#22]
We are working on a fork of this app for a different coin and are stuck on the paper wallet sweep function.  This process starts with scanning a WIF QR Code.

Next, we tested this function on the app from the Google Play store last updated on Jan 20, 2020.  A paper wallet was created with a Legacy address and testnet bitcoins were deposited (4 mBTC).

As seen in this screenshot the amount is found, but the app doesn't progress beyond this screen.

![Screenshot_20200123-103456_Moonshine](https://user-images.githubusercontent.com/5956129/73013458-35e4d280-3dcd-11ea-8183-57f53eb76cf0.jpg)

We haven't tested if this is the case on Bitcoin mainnet, or Litecoin mainnet or testnet.

**Comment by coreyphillips** [comment]
Nice find. Looks like this is due to the [following](https://github.com/coreyphillips/moonshine/blob/1069742b0f7cf04dee7140efbc396241357ae1c6/src/components/SweepPrivateKey.js#L190)

getRecommendedFee is looking for `{coin, transactionSize }` and is causing it to hang. Fix incoming.

**Comment by coreyphillips** [comment]
Should be resolved as of https://github.com/coreyphillips/moonshine/releases/tag/v0.2.0-5
