### ISSUE TITLE
Signatures are not verifying as expected in Bitcoin Core or Electrum

### ISSUE THREAD

**Issue by coreyphillips** [coreyphillips/moonshine#24]
This appears to be due to the following issue in [bitcoinjs-message.](https://github.com/bitcoinjs/bitcoinjs-message/issues/20)

**Comment by coreyphillips** [comment]
This issue should be resolved as of this [commit](https://github.com/coreyphillips/moonshine/commit/1958d1ceeb11d9014ff6027b5e868b7aaf9230b1). Will continue testing.

**Comment by coreyphillips** [comment]
Resolved as of https://github.com/coreyphillips/moonshine/releases/tag/v0.2.0-5

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-message/pull/29#issuecomment-686060820
