### ISSUE TITLE
Remove Litecoin

### ISSUE THREAD

**Issue by 6102bitcoin** [coreyphillips/moonshine#31]
This is an interesting project with some great functionality. 

That said, I (& many others) don't want to be exposed to shitcoins and the associated technical overhead. Litecoin is advertised with misleading information and detracts from this project.

Would you consider removing litecoin support?

**Comment by coreyphillips** [comment]
Hey, glad you find Moonshine interesting.

Regarding Litecoin, I don't intend on removing Litecoin or Litecoin Testnet from Moonshine at this time. However, if you wish to fork the project you can achieve this desired result by removing all instances of "litecoin" & "litecoinTestnet" from the [networks.js file.](https://github.com/coreyphillips/moonshine/blob/master/src/utils/networks.js) I may also create a separate "btc_only" branch in the near future for those requesting this as well.
