### ISSUE TITLE
Android wallet hangs in "Getting current block"

### ISSUE THREAD

**Issue by gabridome** [coreyphillips/moonshine#34]
I set up my own Electrum server and tested and everything seemed fine.
The connection is TCP no SSL on port 5001 (maybe it accepts only ssl connections?).
The "receive" part doesn't give informations.
If I tap "bitcoin" to change currency and I choose "litecoin" then I'm able to get a receiving address (probably because a different server is used?).
When try to come back to the "Bitcoiin" currency there's a screen saying:
"Getting current block, Height and exchange rate..."

Are non SSL connection to an Electrum server allowed. That could be the problem. I need it because I connect through Tor or VPN.
Thank you.
![2020-02-21 16 30 42](https://user-images.githubusercontent.com/460910/75047718-8a13cd00-54c7-11ea-8ee2-5f5d02ba8092.jpg)

**Comment by coreyphillips** [comment]
Hey, sorry you're seeing this issue. 

However, that is correct. The app only accepts ssl connections as of now and will not accept tcp. I'll be sure to make that clearer on the Electrum page. 

I'll also leave this issue open as a feature request to add an ssl/tcp toggle for users such as yourself that may require it.

**Comment by gabridome** [comment]
Perfect.

I think that TCP connections would be useful for Tor or VPM connections where you want your exclusive access to your own node. 
Thank you!

**Comment by coreyphillips** [comment]
A TCP/SSL toggle option has been added as of [this commit](https://github.com/coreyphillips/moonshine/commit/244270af007349d2f066b6fb9ea2dda6888df6a0) and is available for testing in the 0.3.2 beta version of the Android & iOS app. I will leave this issue open in case any testers report issues with the new feature.
<img width="340" alt="Screen Shot 2020-02-22 at 1 26 45 PM" src="https://user-images.githubusercontent.com/8532651/75206250-fc90e100-5743-11ea-83a7-4918d0a9b15c.png">
