### ISSUE TITLE
problem occurred starting process 'command 'security'' - Windows10 Android

### ISSUE THREAD

**Issue by juantellez** [coreyphillips/moonshine#4]
Hi Corey, im trying to run moonshine-0.2.0-2  with windows10 and android but i got this errors.

I will apreciate help.

Thanks

`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command 'security''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================`

**Comment by coreyphillips** [comment]
Hey @juantellez, if you navigate to /android/app/build.gradle you'll see the following lines:
```
def getPassword(String currentUser, String keyChain) {
    def stdout = new ByteArrayOutputStream()
    def stderr = new ByteArrayOutputStream()
    exec {
        commandLine 'security', 'find-generic-password', '-a', currentUser, '-s', keyChain, '-w'
        standardOutput = stdout
        errorOutput = stderr
        ignoreExitValue true
    }
    //noinspection GroovyAssignabilityCheck
    stdout.toString().trim();
}
def currentUser = System.getProperty("user.name");
def keyChainId = "moonshine_android_keystore";
def pass = getPassword(currentUser, keyChainId);
```
Delete that and replace it with:
```
def pass = ""
```

I currently use the keychain available on Macs to create builds. This may be interfering with your builds on Windows/Linux machines. I'll need to eventually implement a new workflow here, but for now this workaround should help.
