### ISSUE TITLE
Share requested amount shows incorrect numbers

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#40]
How to reproduce:

1. Go to settings choose Crypto Units **BTC**
2. Go to Receive
3. Specify amount
4. 12 BTC Ok
5. Press Share
6. send message to Telegram f.e.
7. U will send something like this

Address:
bc1qw5g9s6*****************************d6am2rg

Amount:
1200000000 BTC
$87,513.12

**Comment by coreyphillips** [comment]
Hey cryply, awesome find. Thanks for creating an issue with steps to reproduce. 

I pushed a fix for it [here](https://github.com/coreyphillips/moonshine/commit/5797a7a8e9b939efe2df46381c1673e19fc7c5fe) and intend to include it in the next available build. I'm going to leave this issue open until I've verified that it's been resolved in the next beta build.

**Comment by cryply** [comment]
Works very well!
