### ISSUE TITLE
Restoring of seed phrase needs extra refresh

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#42]
Good time of day!

I found funny behavior:
after recovering wallet from backup seed phrase, we see no money in main screen.

Refresh wallet button not helping in this case somehow.

Only remedy I found till now :
1. Settings
2. click on Legacy
3. click on Segwit,
4. Bech32 
5. Return to main screen 

Now we can see amount of money which was backed up.

**Comment by coreyphillips** [comment]
Hey cryply, sorry to see you're having some issues syncing an imported wallet. Unfortunately, I'm not able to reproduce this issue on my end, but I'll be sure to keep an eye out for it. If you connect to a specific Electrum server feel free to forward that over and I can run some tests and attempt to replicate your results. If you do experience this issue again, you can tap the "Rescan Wallet" button in Settings. It's towards the bottom just above "Support". This option is basically a full rescan where it rescans back from index 0 of the derivation path. The refresh button on the main screen is more of a quick/shallow scan.
