### ISSUE TITLE
Back button do not exits App to Home screen on Android

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#44]
Hi Corey Phillips

On android its normal to press back to exit App but Moonshine is not behaving currently this way.

**Comment by coreyphillips** [comment]
This is expected behavior. If you prefer for the app to exit on back press instead you can modify the onBack method [here](https://github.com/coreyphillips/moonshine/blob/master/src/components/App.js#L298) to return false for the desired behavior.
