### ISSUE TITLE
Back button not working in some screens

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#46]
In "Send" and "Send-CoinControl"
"Back" functionality disabled. Only click on round cross button helps.

**Comment by coreyphillips** [comment]
Good catch! Thanks, cryply. I'm able to reproduce this issue on the "Send Transaction" view as well. I'll dig into this and update this issue accordingly.

**Comment by coreyphillips** [comment]
This should be resolved as of 5c5ddc946e52c0a3fbd54cceb6561b7f6edbe30a and will be available in the next release (0.3.5).
