### ISSUE TITLE
bech32 shows segwit TXs

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#50]
sometimes in TX log of bech32 I see segwit TXs... 
later they disappears.
Honestly I would prefer to have 1 log for all of them.

**Comment by coreyphillips** [comment]
Hey cryply, understood. Moonshine intentionally does not consolidate transactions to Legacy, Segwit & Bech32 addresses as it defaults to the Bech32 address type. I don't intend to add this as a feature in the short term, but if you would like to make a PR please feel free to do-so.
