### ISSUE TITLE
short TX message produce garbage characters

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#52]
Hey Corey

When u send some fund and Optional message is shorter than 5 characters some garbage appears in TX log on blockexplorer or wallet

**Comment by coreyphillips** [comment]
Thanks cryply! I'm able to reproduce this on my end as well. Screenshot attached. Marking this as a bug.
![2020-05-08](https://user-images.githubusercontent.com/8532651/81449327-0c6a6f80-914e-11ea-8a77-756db0448f2b.png)

**Comment by coreyphillips** [comment]
This should be resolved as of b45faf8fd99254f1f84dea230f5d99fa1856847f

Will continue to test.

**Comment by coreyphillips** [comment]
This is available for testing as of 0.3.6.
