### ISSUE TITLE
Invalid currency when sending TX

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#56]
Hey Corey!
Long time no see!.

Small bug found by my colleague. When u send TX USD always shown instead of currency from settings.
![image](https://user-images.githubusercontent.com/36797566/88410015-0c395200-cdd6-11ea-86ec-2f637dc20324.png)

**Comment by coreyphillips** [comment]
Hey, great eye! I'm able to reproduce this on my end as well. I'll mark this as a bug and have a fix prepped for the next release.

**Comment by cryply** [comment]
Hey Corey.
While now we see correct currency, calculation still in USD for me.
Let me show u screenshot  of clone of ur project:
![image](https://user-images.githubusercontent.com/36797566/88476573-a2d25400-cf39-11ea-9c7a-038c17efe33e.png)

**Comment by cryply** [comment]
This happened when I clicked MAX

**Comment by coreyphillips** [comment]
Unfortunately, I wasn't able to reproduce this on my end from master. However, it looks like you may be using a fork/different implementation of the wallet. It may be a similar type of bug to the one found [here](https://github.com/coreyphillips/moonshine/issues/54).
