### ISSUE TITLE
Crypto Units BTC instead of satoshi

### ISSUE THREAD

**Issue by cryply** [coreyphillips/moonshine#57]
Hey Corey

Its not a bug but can u explain how to change default CryptoUnits from satoshi to BTC?
My attempts was always unsuccessful .:(

Thanks mate

**Comment by coreyphillips** [comment]
Hey cryply, sure thing. You'll want to search for the "Crypto Units" option in Settings. So, Settings->Crypto Units-> Select "BTC"

I've attached an image displaying the "Crypto Units" option in the Settings menu as well. If you still have any issues switching over to BTC from satoshi please let me know.

![Screenshot_20200724-170146](https://user-images.githubusercontent.com/8532651/88435417-28d28b80-cdd0-11ea-879d-e862239f980e.png)

**Comment by cryply** [comment]
Hey Corey
Thanks for answer but l wanna know how to do it from programmers perspective. 
Basically how to set unit to BTC by default(using JS RN) at start of app. So users don't need to  go to settings to set it manually.

**Comment by coreyphillips** [comment]
Understood.
To set BTC as the default cryptoUnit for a new app install you'll want to set `cryptoUnit` to "BTC" [here.](https://github.com/coreyphillips/moonshine/blob/37a47941ab42e9625a2e701fb3140e8bbb262aad/src/reducers/settings.js#L36)
To programmatically toggle BTC as the cryptoUnit you can do the following, `this.props.updateSettings({ cryptoUnit: "BTC" });`. An example of this can be seen [here](https://github.com/coreyphillips/moonshine/blob/37a47941ab42e9625a2e701fb3140e8bbb262aad/src/components/Settings.js#L777).

Hope this helps. Let me know if you still have any questions or if this wasn't clear and I'll do my best to clarify.
