### ISSUE TITLE
Receive specific amount doesn't change QR code or text in address field

### ISSUE THREAD

**Issue by martini1992** [coreyphillips/moonshine#58]
Was trying to create an invoice the other day for a few sats, the QR code didn't seem to update per #27 and/or the text in the address field didn't update to the invoice string.

Not completely sure on what the functionality should be so some clarification may be needed.

**Comment by coreyphillips** [comment]
Hey @martini1992, thanks for opening up this issue. I was able to reproduce it on my end as well and hope to have resolved it in [this commit](https://github.com/coreyphillips/moonshine/commit/a8f0f10925527401c60abef6a773329b62c292a8). If resolved, this fix will be included in the v0.3.7 release. I'll leave this issue open in case you or others encounter any more issues in the meantime.
