### ISSUE TITLE
www. prefix on site URL not working, thus "Developer link from Android app download page gets  

### ISSUE THREAD

**Issue by sgornick** [coreyphillips/moonshine#65]
```
$ GET -eSd https://www.moonshinewallet.com
GET https://www.moonshinewallet.com
500 Can't connect to www.moonshinewallet.com:443 (Name or service not known)

```

The link in the Developer website for the app,

https://play.google.com/store/apps/details?id=com.kisswallet

shows 

https://www.moonshinewallet.com

Should either support optional www. subdomain on the website (recommended), or should change the URL on the Android app download page.

**Comment by coreyphillips** [comment]
Thank you much! This should be resolved.
