### ISSUE TITLE
Initial react-native run-ios Failure

### ISSUE THREAD

**Issue by JustinSeidl** [coreyphillips/moonshine#69]
Cloned the repository and trying to run an iOS build but am receiving the below error after following the installation commands:

```
➜  moonshine git:(master) react-native run-ios
info Found Xcode workspace "moonshine.xcworkspace"
info Launching iPhone X (iOS 11.1)
info Building (using "xcodebuild -workspace moonshine.xcworkspace -configuration Debug -scheme moonshine -destination id=A5FF1324-834B-40FA-8E55-A04B9DC8CCF6")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening moonshine.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace moonshine.xcworkspace -configuration Debug -scheme moonshine -destination id=A5FF1324-834B-40FA-8E55-A04B9DC8CCF6

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: /Users/justinseidl/Sites/moonshine/ios/Pods/Target Support Files/Pods-moonshine/Pods-moonshine.debug.xcconfig: unable to open file (in target "moonshine" in project "moonshine") (in target 'moonshine' from project 'moonshine')
error: /Users/justinseidl/Sites/moonshine/ios/Pods/Target Support Files/Pods-moonshine/Pods-moonshine.debug.xcconfig: unable to open file (in target "moonshine" in project "moonshine") (in target 'moonshine' from project 'moonshine')
error: /Users/justinseidl/Sites/moonshine/ios/Pods/Target Support Files/Pods-moonshine/Pods-moonshine.debug.xcconfig: unable to open file (in target "moonshine" in project "moonshine") (in target 'moonshine' from project 'moonshine')
error: /Users/justinseidl/Sites/moonshine/ios/Pods/Target Support Files/Pods-moonshine/Pods-moonshine.debug.xcconfig: unable to open file (in target "moonshine" in project "moonshine") (in target 'moonshine' from project 'moonshine')


** BUILD FAILED **
```

**Comment by JustinSeidl** [comment]
@coreyphillips I am hoping you can help me understand what I am missing?

**Comment by coreyphillips** [comment]
Hey @JustinSeidl. There are a few items that could be causing this issue. I'll list some potential items/solutions coming to mind at the moment:

1. Looks like it may be an issue with the `pod install`. So just to be sure,  updating cocoapods with `sudo gem install cocoapods` may help.
    - And then try a fresh clone, install and start once updated:
      `git clone https://github.com/coreyphillips/moonshine && cd moonshine && yarn install && react-native run-ios`
2. Navigate to the ios directory and attempt to manually run `pod install`. If there were no errors attempt to start the project. 
3. If you navigate to and open `moonshine/ios/moonshine.xcworkspace`, you'll see under "Signing & Capabilities" that "Ferryman Fin LLC" is set as the Team. This could be breaking the build. Changing this to a team of your own or "None" may help. Once done, attempt to start the project. <img width="681" alt="moonshine-s c" src="https://user-images.githubusercontent.com/8532651/111411871-ba6d7100-86b1-11eb-9101-0edcb99eed22.png">

**Comment by JustinSeidl** [comment]
@coreyphillips thank you for the assistance. I ended up having to update pods followed by the pods install.

```
➜  ios git:(master) pod install
Auto-linking React Native modules for target `moonshine`: BVLinearGradient, RNBootSplash, RNCAsyncStorage, RNCClipboard, RNKeychain, RNReactNativeHapticFeedback, RNReanimated, RNSVG, RNVectorIcons, TouchID, lottie-ios, lottie-react-native, react-native-blur, react-native-camera, react-native-netinfo, react-native-randombytes, react-native-slider, and react-native-tcp
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "FlipperKit/SKIOSNetworkPlugin":
  In snapshot (Podfile.lock):
    FlipperKit/SKIOSNetworkPlugin (= 0.54.0, ~> 0.54.0)

  In Podfile:
    FlipperKit/SKIOSNetworkPlugin (~> 0.54.0)

None of your spec sources contain a spec satisfying the dependencies: `FlipperKit/SKIOSNetworkPlugin (~> 0.54.0), FlipperKit/SKIOSNetworkPlugin (= 0.54.0, ~> 0.54.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
➜  ios git:(master) pod repo update
Updating spec repo `trunk`
➜  ios git:(master) pod install
```

**Comment by JustinSeidl** [comment]
@coreyphillips next problem I am running into after installing cocoapods. Appears to be an issue with my bundle?

![Screen Shot 2021-03-17 at 9 25 14 AM](https://user-images.githubusercontent.com/502625/111483420-c46b9000-8702-11eb-8637-dec54c472f08.png)

**Comment by coreyphillips** [comment]
Looks like it might not have spawned the server, so you might need to do it manually. To test this, open up two terminals and navigate to moonshine in each. In one terminal type `yarn start` and in the other run `react-native run-ios`. That should get it going.

**Comment by JustinSeidl** [comment]
@coreyphillips thank you for the tip. It didn't solve my issue launching the iOS version but it did expose the error that I was able to investigate. It turns out the last issue I was experiencing was related to my node version. I was using 12.18.2, switched to 14.16.0 after investigating your package.json, and that solved the issue!

Excited to explore your wallet further. Thank you

![Uploading Screen Shot 2021-03-18 at 8.23.52 PM.png…]()
