### ISSUE TITLE
add .ipa file to github releases

### ISSUE THREAD

**Issue by emanuelb** [coreyphillips/moonshine#72]
Add .ipa file (ios app) to the releases as asset at github releases, which currently have only apk (android app) files:
https://github.com/coreyphillips/moonshine/releases

**Comment by coreyphillips** [comment]
I got you. An ipa for the most recent commit (8353a3ede97e6bae6914d3380257b6e57074cd10) was created and uploaded [here](https://github.com/coreyphillips/moonshine/releases/tag/v0.4.0). Moving forward, I'll upload the .ipa file that corresponds to each release for those that wish to go that route. Please let me know if you have any trouble downloading/installing it.
