### ISSUE TITLE
Ubuntu 18.04 yarn install error

### ISSUE THREAD

**Issue by hungyu99** [coreyphillips/moonshine#79]
Ubuntu 18.04 yarn install error

![z11](https://user-images.githubusercontent.com/37219257/119792890-a8f1e200-bf08-11eb-8081-4731cae7d18e.png)

May I ask what is the problem?
Excuse me, thank you!

**Comment by coreyphillips** [comment]
Hey @hungyu99, looks like you may need to upgrade node to a version that's greater than or equal to version 10. I would recommend using something like [nvm](https://github.com/nvm-sh/nvm) so you can swap to different versions as needed. (Ex: `nvm install 12 && nvm use 12`).
