### ISSUE TITLE
Is this app abandoned?

### ISSUE THREAD

**Issue by menaceone** [coreyphillips/moonshine#85]
* last release is from 2020 (and not available in app stores)
* last commit is from May 2021
* last issue is from May 2021

I like Moonshine for its electrum server option and foremost for its OP_RETURN support but it seems development is halted.
I came here for reporting an Issue regarding wrong display of send transactions but it seems I have to switch to another wallet.

@coreyphillips could you write a statement and update the main README.md?

**Comment by coreyphillips** [comment]
I only intend to minimally support this project as needed at this time. If you would prefer a Bitcoin wallet with more active development I would suggest [Bitkit](https://github.com/synonymdev/bitkit).
